#################################################
# Recipe Manipulation Config
#################################################
# recipeModifications:                     # <- This is the top level key, all modifications live under this, it is required.
#   DisableWoodArrow:                      # <- This is the modification name, its primarily for you to understand what this modification does SHOULD BE UNIQUE
#     action: Disable                      # <- This is the action it should be one of [Disable, Delete, Modify, Add, Enable]
#     prefab: ArrowWood                    # <- This is the prefab that the modification will target
#   AddNewWoodArrowRecipe:
#     action: Add
#     prefab: ArrowWood
#     recipeName: Recipe_ArrowWood         # <- optional, specifying the recipe name allows multiple mutating multiple recipes targeting the same prefab
#     craftedAt: Workbench                 # <- The crafting station that should craft this recipe, leave it empty or invalid for handcrafting
#     minStationLevel: 2                   # <- This is the required crafting station level for discovery AND crafting
#     recipe:                              # <- When performing [Modify] or [Add] you should define a recipe
#       anyOneResource: false              # <- This makes the recipe only require one ingrediant, first from the top will be used.
#       ingredients:                       # <- Ingrediants in the recipe, is an array
#         - prefab: Wood                   # <- Prefab that this ingrediant requires
#           craftCost: 2                   # <- The amount of this ingrediant it takes to craft the recipe  
#           upgradeCost: 0                 # <- The amount of this ingrediant it takes to upgrade the item 
#           refund: false                  # <- Whether or not this recipe refunds  
#         - prefab: Feathers
#           craftCost: 2
#           upgradeCost: 0
#           refund: true
#   DeleteTrollHideArmorRecipe:
#     action: Delete
#     prefab: CapeTrollHide
#   ModifyTrollHideChestRecipe:
#     action: Modify
#     prefab: ArmorTrollLeatherChest
#     craftedAt: Workbench
#     minStationLevel: 1
#     recipe:
#       anyOneResource: false
#       ingredients:
#         - prefab: TrollHide
#           craftCost: 4
#           upgradeCost: 2
#           refund: false

recipeModifications:
  Add_Convert_Resources_Wood_Stone:
    action: Add
    prefab: Stone
    recipeName: ACR_Wood_Stone
    craftedAt: piece_stonecutter
    minStationLevel: 1
    craftAmount: 1
    recipe:
      anyOneResource: false
      ingredients:
      - prefab: Wood
        craftCost: 1

  Add_Convert_Resources_Stone_Wood:
    action: Add
    prefab: Wood
    recipeName: ACR_Stone_Wood
    craftedAt: piece_stonecutter
    minStationLevel: 1
    craftAmount: 1
    recipe:
      anyOneResource: false
      ingredients:
      - prefab: Stone
        craftCost: 1

  Add_Convert_Resources_Wood_Stone_10x:
    action: Add
    prefab: Stone
    recipeName: ACR_Wood_Stone_10x
    craftedAt: piece_stonecutter
    minStationLevel: 1
    craftAmount: 10
    recipe:
      anyOneResource: false
      ingredients:
      - prefab: Wood
        craftCost: 10

  Add_Convert_Resources_Stone_Wood_10x:
    action: Add
    prefab: Wood
    recipeName: ACR_Stone_Wood_10x
    craftedAt: piece_stonecutter
    minStationLevel: 1
    craftAmount: 10
    recipe:
      anyOneResource: false
      ingredients:
      - prefab: Stone
        craftCost: 10

