
"SB Miner's Bag":
  description: "An essential heavy bag for miners, optimized for carrying ores and stones. Lightens their weight by 10%."
  size: 4x4 # Initial size with 2 columns and 4 rows.
  unique: type
  appearance:
    Sleepbag: 000000
    BackpackStrapTop: hidden
    BackpackFlap: 000000
    BackpackBody: 000000
    Pickaxe: 000000
    Pot: hidden
    Teapot: hidden
    Knife: 000000
    Knifesheath: hidden
    ToolstrapBottom: 000000
    MetalclipLeft: hidden
    PouchFront: 000000
    PouchLeft: 000000
  crafting:
    station: Forge
    level: 1
    costs:
      LeatherScraps: 5
      DeerHide: 5
      FoxPelt_TW: 2
      WoolScraps_TW: 1
  valid items:
    - TinOre
    - CopperOre
    - IronOre
    - Stone
    - Coal
    - Copper
    - Flametal
    - FlametalNew
    - FlametalOre
    - FlametalOreNew
    - Flint
    - IronScrap
    - CopperScrap
    - Iron
    - Crystal
    - Obsidian
    - Chitin
    - Tin
    - Bronze
    - Silver
    - BlackMetal
    - BlackMetalScrap
    - SilverOre
    - BlackMarble
    - Grausten
    - Softtissue
    - Onyx_TW
    - Mortar_TM
    - BRP_RefinedStone
    - PlatinumOre_RS
    - Platinum_RS
  upgrade:
    1:
      TrollHide: 2
      SurtlingCore: 1
      size: 6x4
    2:
      Entrails: 5
      Bloodbag: 5
      Root: 1
      size: 8x4
  weight factor: 1
  teleport: true

"SB Tool Belt":
  description: "A versatile heavy belt designed for builders, containing all the essential hammers and tools for construction. Lightens their weight by 10%"
  size: 4x4 # Initial size with 2 columns and 4 rows.
  unique: type
  appearance:
    Sleepbag: 531e1e
    BackpackStrapTop: b09078 
    BackpackFlap: 949494
    Pickaxe: b09078 
    Pot: hidden
    BackpackBody: 531e1e
    Teapot: hidden
    Knife: hidden
    Knifesheath: hidden
    ToolstrapBottom: b09078 
    MetalclipLeft: b09078 
    PouchFront: 949494 
    PouchLeft: 949494
  crafting:
    station: Forge
    level: 1
    costs:
      LeatherScraps: 5
      DeerHide: 5
      FoxPelt_TW: 2
      WoolScraps_TW: 1
  valid items:
    - Cultivator
    - Hammer
    - Hoe
    - bp_hammer
    - GB_Parchment_Tool
    - BJORKSNAS
    - $PlumgaPlantItShovel
    - $PlumgaClutterTool
    - remotecontrol
    - TBPHammer_TP
    - DirtyHoe
    - odin_hammer
    - StoneChisel
    - rkc_scepter
    - rk_hammer
    - BHP_OdinsHand
    - AncientScroll
    - OP_Bamboo_Hammer
    - IronNails
    - BronzeNails
    - PickaxeAntler
    - PickaxeBronze
    - PickaxeIron
    - PickaxeStone
    - PickaxeSilver_TW
    - PickaxeBlackMetal
    - PickaxeFader_TW
    - VABlood_Bones_pickaxe
    - AxeIron
    - AxeBronze
    - AxeSilver_TW
    - AxeBlackMetal
    - AxeFlint
    - AxeStone
    - BattleaxeCrystal
    - BattleaxeCrystal_TW
    - BattleaxeCrystalEmerald_TW
    - BattleaxeCrystalAmethyst_TW
    - VAbronze_battleaxe
    - KnifeButcher
    - ef_hammer
    - Feaster
    - Scythe
    - ScytheHandle
    - BarrelRings
    - VillageHammer
    - RS_LanternOrb
    - RS_Lantern
    - Lantern
    - piece_dvergr_BetterHandLantern
    - piece_dvergr_WispHandLantern
  upgrade:
    1:
      TrollHide: 2
      SurtlingCore: 1
      size: 6x4
    2:
      Entrails: 5
      Bloodbag: 5
      Root: 1
      size: 8x4
  weight factor: 1
  teleport: true

"SB Enchanting Pouch":
  description: "A small mystical pouch designed for enchanters, perfect for carrying essence, dust, shards, reagents, and runestones. Lightens their weight by 20%"
  size: 4x4 # Initial size with 2 columns and 4 rows.
  unique: type
  appearance:
    Sleepbag: hidden
    BackpackStrapTop: hidden
    BackpackFlap: 9f00f3
    Pot: 9f00f3
    Teapot: 9f00f3
    Knife: hidden
    Pickaxe: hidden
    Knifesheath: hidden
    ToolstrapBottom: hidden
    MetalclipLeft: hidden
    PouchFront: 9f00f3
    PouchLeft: 9f00f3
    BackpackBody: 000000
  crafting:
    station: Forge
    level: 1
    costs:
      LeatherScraps: 5
      DeerHide: 5
      FoxPelt_TW: 2
      WoolScraps_TW: 1
  valid items:
    - RunestoneMagic
    - RunestoneRare
    - RunestoneEpic
    - RunestoneLegendary
    - RunestoneMythic
    - ShardMagic
    - ShardRare
    - ShardEpic
    - ShardLegendary
    - ShardMythic
    - DustMagic
    - DustRare
    - DustEpic
    - DustLegendary
    - DustMythic
    - ReagentMagic
    - ReagentRare
    - ReagentEpic
    - ReagentLegendary
    - ReagentMythic
    - EssenceMagic
    - EssenceRare
    - EssenceEpic
    - EssenceLegendary
    - EssenceMythic
    - ForestToken
    - IronBountyToken
    - GoldBountyToken
    - SDO_dim_eitr
    - SDO_capsule
    - SDO_cogwheel
    - SDO_book
    - SDO_divine_orb
    - SDO_sand
    - SDO_books_tales
    - DimEitrRemnantDO
    - SpiritLightDO
    - SpiritDeathDO
    - SpiritFrostDO
    - SpiritFireDO
    - SpiritStormDO
    - SpiritAncestorsDO
    - SpiritWindDO
  upgrade:
    1:
      TrollHide: 2
      SurtlingCore: 1
      size: 6x4
    2:
      Entrails: 5
      Bloodbag: 5
      Root: 1
      size: 8x4
  weight factor: 1
  teleport: true
